# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # blogin kirjoituksen työasema
  config.vm.define "blag" do |blag|
    blag.vm.box = "CentOS-7.0"
    blag.vm.box_url = "https://s3-eu-west-1.amazonaws.com/solita-images/centos-7.0-x86_64.box"

    blag.vm.synced_folder "../", "/env"
    blag.vm.provision "shell", inline: "cd /env/vagrant && ./makeitso.sh"

    # local port 4444 -> vm port 4000
    blag.vm.network "forwarded_port", host: 4444, guest: 4000
  end
end
